# Generated by Django 3.0.14 on 2022-04-25 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PredResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Test199', models.IntegerField()),
                ('Test220', models.IntegerField()),
                ('Test215', models.IntegerField()),
                ('Test14', models.IntegerField()),
                ('Test20', models.IntegerField()),
                ('Test22', models.IntegerField()),
                ('Test55', models.IntegerField()),
                ('Test1', models.IntegerField()),
                ('Test54', models.IntegerField()),
                ('Test57', models.IntegerField()),
                ('Heart_Disease', models.CharField(max_length=30)),
                ('auther', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predict_predict', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
