# Generated by Django 3.0.14 on 2022-04-25 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predresults',
            name='auther',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='predict_predict', to=settings.AUTH_USER_MODEL),
        ),
    ]
